### ISSUE TITLE
feat: allow optionally installing dependencies via pip (like `gooey`) in `test-on-pr.yml`

### ISSUE THREAD

**Issue by bobleesj** [scikit-package/release-scripts#164]
### Problem

Atm, our CI must install everything from `conda.txt`. But in the case of `regolith`, it is required to install `gooey` via pip. 

Hence, `regolith` atm can't use our beautiful reusable script. 

Ref: https://github.com/regro/regolith/pull/1258

### Proposed solution

Allow optional `pip_install` section? Please see an example below:

```
jobs:
  tests-on-pr:
    uses: scikit-package/release-scripts/.github/workflows/_tests-on-pr.yml@v0
    with:
      project: regolith
      c_extension: false
      headless: false
      pip_install: gooey
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
```
